#!/bin/sh
chown _runit-log:adm '/var/log/runit/ssh'
chmod 750 '/var/log/runit/ssh'
# temporary fix for log user change
rm -f '/var/log/runit/ssh/lock'
if [ -f '/var/log/runit/ssh/current' ]; then
    logusr="$(stat --format '%U' '/var/log/runit/ssh/current')"
    if [ "${logusr}" = "runit-log" ]; then
        chown _runit-log:adm '/var/log/runit/ssh/current'
    fi
fi
exec chpst -u _runit-log svlogd -tt '/var/log/runit/ssh'
